language: generic
env:
  global:
    - IDE_VERSION=1.8.9
  matrix:
    - BOARD="arduino:samd:mkrzero"

before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd &> /dev/null;
    fi
  - buildExampleSketch() { arduino --verify --board $BOARD $1; }
  - oldBuildExampleSketch() {  arduino --verify --board $BOARD $PWD/examples/$1/$1.ino; }
  - badBuildExampleSketch() {  arduino --verify --board $BOARD $PWD/examples/tempBad/$1/$1.ino; }
  -  |
     buildAllExamples(){
       declare -a failureList=()
       local failureNum=0
       shopt -s globstar
       for i in $PWD/examples/**/*.ino; do
         echo $i
         buildExampleSketch $i
         exit_status=$?
         if [ $exit_status != 0 ]; then
           failureNum=$((failureNum + 1))
           echo Failure Building: $i
           failureList+=($i)
         else
           echo Build Successful: $i
         fi
       done
       
       for i in "${arr[@]}"; do
         echo Failure to build: $i
       done
       echo $failureNum
       return $failureNum;
      }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/travisTesting
script:
-  |
  buildAllExamples

  


