language: generic
env:
  global:
    - IDE_VERSION=1.8.9
  matrix:
    - BOARD="arduino:samd:mkrzero"

before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd &> /dev/null;
    fi
  - buildExampleSketch() { arduino --verify --board $BOARD $PWD/examples//$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/travisTesting
script:
-  |
  for i in $HOME/Arduino/libraries/travisTesting/examples/**/*.ino; do
      buildExampleSketch $i
  done
